# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1
cache:
  directories:
  - $HOME/.julia/artifacts
env:
  - DOCUMENTER_DEBUG=true
notifications:
  email: false
script:
  - julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
  - julia --project=. --color=yes docs/make.jl
